# Accessing values in 1d array

In [2]:
#throgh single index
import numpy as np
a = np.array([1,2,3,4,5])
a[3] = 12
a

array([ 1,  2,  3, 12,  5])

In [15]:
#throgh multiple index
a[[1,2,3,4]]

array([ 2,  3, 12,  5])

In [13]:
#throgh slicing
a[1:4]

array([ 2,  3, 12])

In [17]:
#mask indexing(by condition)
a[a%2==0]

array([ 2, 12])

# Functions  

In [26]:
#arange(syntax = np.arange(start,end))
a = np.arange(1,9)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
#zeros(syntax = np.zeros([shape]))
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
#ones(syntax = np.ones([shape]))
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
#linspace(syntax = np.linspace(start,end,no.of samples))
np.linspace(1,4,5)


array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [25]:
#random.randint(syntax = np.zeros(start,end,no. of samples))
np.random.randint(1,40,5)

array([29,  8, 24, 30, 15])

In [47]:
#sort
np.sort([20,12,28,15,52])

array([12, 15, 20, 28, 52])

In [ ]:
#copy
b = a.copy()
a
b

# Modification in 1D arrays 

In [27]:
#By Adding single element
np.append(a,110)

array([  1,   2,   3,   4,   5,   6,   7,   8, 110])

In [41]:
#By Adding multiple elements
np.append(a,[10,20,30])

array([ 1, 35, 56, 56, 56,  6,  7,  8, 10, 20, 30])

In [42]:
#By Replacing single element
a[3] = 24
a


array([ 1, 35, 56, 24, 56,  6,  7,  8])

In [40]:
a[[3,4,2]]= 56
a

array([ 1, 35, 56, 56, 56,  6,  7,  8])

In [34]:
#By Replacing multiple elements
a[[1,2,3]]= [35,67,23]
a

array([ 1, 35, 67, 23,  5,  6,  7,  8])

In [44]:
#By deleting single element
np.delete(a,3)

array([ 1, 35, 56, 56,  6,  7,  8])

In [46]:
#By deleting multiple elements
np.delete(a,[4,6,2])

array([ 1, 35, 24,  6,  8])

# Operators

In [4]:
#Arithmetic Operators
a = np.array([1,2,3])
b = np.array([3,4,5])
a+b

array([4, 6, 8])

In [51]:
a-b

array([-2, -2, -2])

In [52]:
a*b

array([ 3,  8, 15])

In [53]:
a/b

array([0.33333333, 0.5       , 0.6       ])

In [54]:
#Comparison Operators
a==b

array([False, False, False])

In [55]:
a<b

array([ True,  True,  True])

In [56]:
a>b

array([False, False, False])

In [58]:
a<=b

array([ True,  True,  True])

In [60]:
a>=b

array([False, False, False])

In [5]:
np.array_equal(a,b)

False

In [7]:
c = np.array([1,2,3])
np.array_equal(a,c)

True

In [61]:
#Mathematical Operators
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [62]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [63]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [64]:
#Statastics
np.mean(a)

2.0

In [65]:
np.median(a)

2.0

In [66]:
np.std(a)

0.816496580927726