# Creating Numpy Arrays

# 0 D Array

In [2]:
import numpy as np
np.__version__

'1.24.3'

In [3]:
#0D array
a_0 = np.array(34)
print(a_0)

34


In [ ]:
#dimension check
a_0.ndim

In [16]:
#shape
a_0.shape

()

# 1 D Array


In [17]:
a_1 = np.array([1,2,3])
print(a_1)

[1 2 3]


In [18]:
#dimension
a_1.ndim

1

In [20]:
a_1.shape

(3,)

# 2 D Array

In [22]:
a_2 = np.array([[1,2,3],[4,5,6]])
a_2

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
#dimension
a_2.ndim

2

In [25]:
#shape
a_2.shape

(2, 3)

# 3 D Array

In [26]:
a_3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a_3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [27]:
#dimension
a_3.ndim

3

In [28]:
a_3.shape

(1, 3, 3)