# Creating Numpy Arrays

# 0 D Array

In [4]:
import numpy as np
np.__version__

'1.26.4'

In [5]:
#0D array
a_0 = np.array(34)
print(a_0)

34


In [6]:
#dimension check
a_0.ndim

0

In [7]:
#shape
a_0.shape

()

# 1 D Array


In [8]:
a_1 = np.array([1,2,3])
print(a_1)

[1 2 3]


In [9]:
#dimension
a_1.ndim

1

In [10]:
a_1.shape

(3,)

# 2 D Array

In [11]:
a_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
#dimension
a_2.ndim

2

In [13]:
#shape
a_2.shape

(3, 3)

# 3 D Array

In [14]:
a_3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a_3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [15]:
#dimension
a_3.ndim

3

In [16]:
a_3.shape

(1, 3, 3)