# Numpy Function 2 dimensional

In [2]:
#diagonal 
import numpy as np
l = [1,2,3,4,5]
np.diag(l)


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [10]:
l=np.array([[1,2,3],[4,5,6],[7,8,9]])
l
np.diag(l)


array([1, 5, 9])

In [13]:
#identity
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
#zeros
a = np.zeros([2,2])
a
np.zeros([2,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
#ones
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Arithmetic Operation

In [4]:
a = np.array([[1,2],[2,3],[3,4]])
b = np.array([[2,3],[3,4],[5,6]])
c =a+b
print(c)

[[ 3  5]
 [ 5  7]
 [ 8 10]]


In [5]:
print(a-b)

[[-1 -1]
 [-1 -1]
 [-2 -2]]


In [6]:
print(a*b)

[[ 2  6]
 [ 6 12]
 [15 24]]


In [7]:
print(a/b)

[[0.5        0.66666667]
 [0.66666667 0.75      ]
 [0.6        0.66666667]]


# Functions

In [27]:
#matmul
a = np.array([[1,2],[5,6]])
b = np.array([[11,33],[55,66]])
np.matmul(a,b)

array([[121, 165],
       [385, 561]])

In [29]:
#flatening(nD-->1D)
a = np.array([[1,2,3],[4,5,6]])
b = a.ravel()
b

array([1, 2, 3, 4, 5, 6])

In [5]:
#reshape
a = np.array([[1,2,3,4],[3,4,5,6]])
a.reshape(4,2)
a

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [49]:
#sort
a = np.array([[23,14,13],[11,42,33]])
a = np.sort(a,axis = 0)
a

array([[11, 14, 13],
       [23, 42, 33]])

In [50]:
np.sort(a,axis = 1)

array([[11, 13, 14],
       [23, 33, 42]])

In [6]:
#concatenate
np.concatenate(a,axis=0)

array([1, 2, 3, 4, 3, 4, 5, 6])

In [13]:
b = np.array([[1,2,3],[4,5,6]])
np.concatenate((a,b),axis =1)

array([[  1,   2,   3,   1,   2,   3],
       [ 10, 200,  30,   4,   5,   6]])

In [16]:
np.hstack([a,b])

array([[  1,   2,   3,   1,   2,   3],
       [ 10, 200,  30,   4,   5,   6]])

In [14]:
np.concatenate((a,b),axis =0)

array([[  1,   2,   3],
       [ 10, 200,  30],
       [  1,   2,   3],
       [  4,   5,   6]])

In [17]:
np.vstack([a,b])

array([[  1,   2,   3],
       [ 10, 200,  30],
       [  1,   2,   3],
       [  4,   5,   6]])

# Accesing Values in 2 D

In [3]:
#By single index
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a[1] = [10,20,30]
a

array([[ 1,  2,  3],
       [10, 20, 30]])

In [7]:
#By multiple index
a[1,1] = 200
a

array([[  1,   2,   3],
       [ 10, 200,  30]])

In [5]:
#By slicing
a[1:3,1:3]

array([[200,  30]])

In [62]:
a[1:3]

array([[10, 20, 30]])